# This is a basic workflow to help you get started with Actions

name: Build AuroriaBot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup the required dotnet core version
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore .\src\AuroriaBot\

      # Build the bot
      - name: Build
        run: dotnet build .\src\AuroriaBot\ --configuration Release --no-restore
